//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerSkillHub.Masterpages
{
    public partial class Site
    {
        protected global::System.Web.UI.WebControls.PlaceHolder phGuest;
        protected global::System.Web.UI.WebControls.PlaceHolder phLoggedIn;
        protected global::System.Web.UI.WebControls.PlaceHolder phStudent;
        protected global::System.Web.UI.WebControls.PlaceHolder phAdmin;
        protected global::System.Web.UI.WebControls.PlaceHolder phInstructor;
        protected global::System.Web.UI.WebControls.Literal litWelcome;
        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;
    }
}